### ISSUE TITLE
Startup warning about ExpressionFactory.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw-web-blank#427] opened 2020-01-23 09:19 UTC
## Description
Environment: Tomcat 9.x (`mvn cargo:run`)

v5.5.1, The following warning is output in the startup log.
```
date:2020-01-23 18:06:22        thread:main     X-Track:        level:WARN
logger:c.github.dozermapper.core.el.ELExpressionFactory message:javax.el is not supported; Failed to resolve ExpressionFactory, com.sun.el.ExpressionFactoryImpl
```
Does not output in v5.4.2.

This problem is believed to have been caused by Dozer version up to 6.x (#366) .

## Possible Solutions
One solution is... add `com.sun.el.ExpressionFactoryImpl` as dependency.
```xml
<dependency>
    <groupId>com.sun.el</groupId>
    <artifactId>el-ri</artifactId>
    <version>1.0</version>
</dependency>
```

## Affects Version/s
- 5.6.0.RELEASE

## Fix repositories
~~- [ ] terasoluna-gfw-web-blank~~
~~- [ ] m-j~~
~~- [ ] m-t~~

**Comment by btiwahorisu** [comment] 2020-02-04 10:21
### Description
The cause of [Warning](https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/427#issue-554032412) occurs because EL is an optional function in Dozer, so dependent libraries cannot be referenced.
### Workaround
The workaround is to add the following to the dependency and enable the EL to reference the library.
```
<dependency>
    <groupId>javax.el</groupId>
    <artifactId>javax.el-api</artifactId>
    <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.el</artifactId>
    <version>3.0.0</version>
</dependency>
```
https://dozermapper.github.io/gitbook/documentation/expressionlanguage.html

**Comment by btiwahorisu** [comment] 2020-02-04 10:28
###  検討内容
Consider based on https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/427#issuecomment-581839693 ,https://github.com/terasolunaorg/terasoluna-gfw-web-blank/pull/428#pullrequestreview-349077162 .

#### the library to be described
> As you incorporate more libraries, you should first discuss whether com.sun.el: el-ri is appropriate.

We considered `com.sun.el: el-ri` for the library that defines the dependency in order to avoid the warning, but this is an ad-hoc response such as adding it because there is no target library. Therefore, it should not be clearly defined in a blank project.

From [Dozer's Guide](https://dozermapper.github.io/gitbook/documentation/expressionlanguage.html), if you want to enable EL, use `javax.el: javax.el-api`,` org.glassfish: javax Guided to define .el` in dependencies.
Since this issue avoids Dozer-related Waring, it is considered appropriate to follow Dozer guidelines. In the TERASOLUNA common library, [javax.el: javax.el-api: 3.0.1-b06](https://github.com/terasolunaorg/terasoluna-gfw/blame/master/terasoluna-gfw-parent/pom.xml#L482-L484) is defined.

Based on the above, the library to be added seems to be `org.glassfish: javax.el: 3.0.1-b06`.

#### place to describe
> If it prints in all environments, you should discuss whether to include com.sun.el: el-ri in your Dozer dependencies.

> if you include a library that is not managed by Spring Boot in your dependencies, you should discuss whether or not to manage the version with terasoluna-gfw-parent.

Since the corresponding Warning implements el implementation class in middleware (tomcat, jboss, etc.),
Occurs only when executed by Cargo.
Based on the above, there are three patterns for the description policy.

1. __Defining dependencies for blank projects__
Since the corresponding Warning occurs in the blank project bean definition,
It seems appropriate to respond with a blank project.
In addition, since it occurs only when activated by Cargo,
It is necessary to control using profile so that other middleware is not affected.

1. __Define in blank project but comment out__
The addition of `org.glassfish: javax.el` is to avoid displaying Warning,
We believe that the priority is low because there is no effect on the application whether or not it actually responds.
Therefore, the following comments and dependencies are commented out and defined,
Have the user change it if necessary.
    - Warning log is generated by Dozer's EL function when executing with cargo.  
To avoid the warning, enable this dependency.

1. __Dependency definition for terasoluna-gfw-parent__
Define `org.glassfish: javax.el: 3.0.1-b06` in terasoluna-gfw-parent.
However, since the guidelines do not use EL features,
There is little need to define it in the common library.

**Comment by btiwahorisu** [comment] 2020-02-04 10:31
> From Dozer's Guide, if you want to enable EL, use javax.el: javax.el-api, org.glassfish: javax Guided to define .el in dependencies.

According to Dozer's guide, `org.glassfish: javax.el` was only used during the Dozer test, and it does not seem to be said that it can be used.
Basically, I think we should follow (close to) our stack.

> Since the corresponding Warning implements el implementation class in middleware (tomcat, jboss, etc.),Occurs only when executed by Cargo.

Cargo runs Tomcat. It should not occur only in Cargo, not in normal Tomcat. (If only Cargo, it is better to investigate the cause including the result different from normal Tomcat)

> In addition, since it occurs only when activated by Cargo,It is necessary to control using profile so that other middleware is not affected.

No such control is needed. Do not complicate the blank.

> Define in blank project but comment out

If it happens with Tomcat, do not comment it out.
(Because there is already something added by default for Tomcat, it should be aligned)

If it's deterministic that Cargo only happens, you don't even need to comment out.
(Because it is not assumed that it will work in Cargo)

**Comment by btiwahorisu** [comment] 2020-02-04 10:35
> If it happens with Tomcat, do not comment it out.(Because there is already something added by default for Tomcat, it should be aligned)

> If it's deterministic that Cargo only happens, you don't even need to comment out.(Because it is not assumed that it will work in Cargo)

I checked the presence of Warning with the tomcat built with the VM, but when I installed and checked tomcat in the local environment, as you pointed out, it was confirmed that Warning was output like Cargo.

Therefore, to avoid Warning in tomcat,
__"Add dependency of el execution library to blank project without commenting out"__ 
We believe it is a correct response.

> According to Dozer's guide, `org.glassfish: javax.el` was only used during the Dozer test, and it does not seem to be said that it can be used.Basically, I think we should follow (close to) our stack.

In sping-boot, the implementation library `org.glassfish: jakarta.el` of el is defined,
[Reason for link](https://github.com/terasolunaorg/management/issues/81#issue-540159273) Because `jakarta` cannot be used, other libraries need to be defined independently.
The following are the implementation libraries for el.
  - `org.glassfish:javax.el`
  - `com.sun.el:el-ri`

`org.glassfish: javax.el` is a library provided from the same grassfish as` javax.el: javax.el-api` defined in the common library, and defines the interface and implementation library together I think that is reasonable.
On the other hand, there is little information about `com.sun.el: el-ri` and it cannot be determined whether it is appropriate.
Also, this library has not been updated since 2008, so I feel that there is little intention to adopt an old library.
Therefore, I think you should define __`org.glassfish: javax.el`__.

**Comment by btiwahorisu** [comment] 2020-02-04 10:39
In the first place, there should be no assumption that you have to choose between `glassfish` or` com.sun`.

- What is the reason for the warning
- What is the difference between the behavior of VM Tomcat and local Tomcat
- Is it necessary to avoid Warning in the first place?

At least after clarifying the above, you will consider the following solutions.

- What can be done to avoid the warning (whether adding a library is the only solution)
- Which libraries are appropriate or proactive?

As you can see from reading the source code, Dozer's [ELExpressionFactory](https://github.com/DozerMapper/dozer/blame/master/core/src/main/java/com/github/dozermapper/core/el/ELExpressionFactory.java#L84-L87) loads the `com.sun.el.ExpressionFactoryImpl` class by default as the implementation class for` ExpressionFactory`. (Warning if this is missing)
The class used can be changed with the `javax.el.ExpressionFactory` system property. As a result, I was able to avoid Warning by using Tomcat's (`jasper-el`)` ExpressionFactoryImpl` class with `-Djavax.el.ExpressionFactory = org.apache.el.ExpressionFactoryImpl`.
I set it as follows because I did it with Cargo.

```xml
<plugin>
  <groupId>org.codehaus.cargo</groupId>
  <artifactId>cargo-maven2-plugin</artifactId>
  <configuration>
      <container>
          <systemProperties>
              <javax.el.ExpressionFactory>org.apache.el.ExpressionFactoryImpl</javax.el.ExpressionFactory>
          </systemProperties>
      </container>
  </configuration>
</plugin>
```

By the way, `tomcat-embed-el` defined in the blank project also contains` org.apache.el.ExpressionFactoryImpl` class.

**Comment by btiwahorisu** [comment] 2020-02-05 02:37
@yoshikawaa 
> What is the reason for the warning

As you pointed out, Warning occurs because the library of default setting `com.sun.el.ExpressionFactoryImpl` does not exist in the class path and cannot be loaded.
Since Dozer 6.2.0, ELengine is set by default when creating an instance, and ELExpressionFactory checks the EL library.
https://github.com/DozerMapper/dozer/blob/6.2.0/core/src/main/java/org/dozer/DozerBeanMapperBuilder.java#L521

Dozer also has a issues with this warning.
https://github.com/DozerMapper/dozer/issues/780

> What is the difference between the behavior of VM Tomcat and local Tomcat

I'm sorry. This was a mistake in checking the application log. __"The same Warning occurs in tomcat of VM"__ is the correct event.
Therefore, it is a Warning that occurs under any environment in the current implementation.

> Is it necessary to avoid Warning in the first place?
The need to avoid warnings is low for the following reasons:
  - Dozer EL functions are not supported because they are not used in Terasoluna guideline.
  - This is not a content that should be addressed in Terasoluna, as it is a phenomenon listed as a known issue in Dozer.

Let me know what you think.

**Comment by yoshikawaa** [comment] 2020-02-06 10:59
I think... it is insincere to keep warning logs out without any solution.
Modifying a blank project to support dependency contains `com.sun.el.ExpressionFactoryImpl` just to suppress warnings is exaggerated and unnecessary. However, it is fact that a warning will be issued, and some users may be concerned about this. For this reason, it is appropriate to make the following announcement in the guidelines.
* Expression Language can be used in the mapping definition XML file
* By default, `com.sun.el.ExpressionFactoryImpl` is loaded to use EL. (You can change using System Property `javax.el.ExpressionFactory` :: **This is important to match EL behavior.**)
* As described in Dozer's Issue, warnings can be ignored or suppressed.

**Comment by btiwahorisu** [comment] 2020-02-12 10:16
@yoshikawaa 
I agree with your opinion.
Create an issue in the guidelines to add a note for the content you have suggested.

**Closed** 2020-06-05 00:49 UTC
Labels: action: migration-guide, status: wontfix, type: bug, version: 5.6.0
